/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package genesezMM.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link genesezMM.MElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MElementValidator
{
  boolean validate();

  boolean validateName(String value);
  boolean validateXmiGuid(String value);
  boolean validateOwnedComment(EList value);
  boolean validateTaggedValue(EList value);
  boolean validateStereotype(EList value);
  boolean validateAspect(EList value);
}
