/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package genesezMM.validation;

import genesezMM.MOperation;
import genesezMM.MType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link genesezMM.MParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MParameterValidator
{
  boolean validate();

  boolean validateDefaultvalue(String value);
  boolean validateDirection(String value);
  boolean validateMultiplicity(int value);
  boolean validateUnique(boolean value);
  boolean validateOrdered(boolean value);
  boolean validateOperation(MOperation value);
  boolean validateGenericRealization(EList value);
  boolean validateType(MType value);
}
