/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.genesez.metamodel.genesezMM.validation;

import de.genesez.metamodel.genesezMM.MClass;
import de.genesez.metamodel.genesezMM.MPackage;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.genesez.metamodel.genesezMM.MAssociation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MAssociationValidator
{
  boolean validate();

  boolean validateDerived(boolean value);
  boolean validateEnd(EList value);
  boolean validateOwningPackage(MPackage value);
  boolean validateAssociationClass(MClass value);
}
