/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package genesezMM.validation;

import genesezMM.MComment;
import genesezMM.MElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link genesezMM.MComment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MCommentValidator
{
  boolean validate();

  boolean validateXmiGuid(String value);
  boolean validateAnnotation(String value);
  boolean validateOwningElement(MElement value);
  boolean validateNestedComment(EList value);
  boolean validateNestingComment(MComment value);
}
