/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package genesezMM.validation;

import genesezMM.MClassifier;
import genesezMM.MExternal;
import genesezMM.MOperation;
import genesezMM.MParameter;
import genesezMM.MProperty;

/**
 * A sample validator interface for {@link genesezMM.MGeneric}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MGenericValidator
{
  boolean validate();

  boolean validateSpecification(String value);
  boolean validateOwningClassifier(MClassifier value);
  boolean validateOwningOperation(MOperation value);
  boolean validateOwningProperty(MProperty value);
  boolean validateOwningParameter(MParameter value);
  boolean validateOwningExternal(MExternal value);
}
