/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package genesezMM.validation;

import genesezMM.MPackage;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link genesezMM.MPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MPackageValidator
{
  boolean validate();

  boolean validateNestedPackage(EList value);
  boolean validateNestingPackage(MPackage value);
  boolean validateAssociation(EList value);
  boolean validateClassifier(EList value);
}
