<?xml version="1.0" encoding="UTF-8"?>
<genesezMM:MModel xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:genesezMM="/genesezMM/genesezMM" name="sampleCodegen"
    xmiGuid="eee_1045467100313_135436_1">
  <ownedComment xmiGuid="_11_5_6340215_1177945794093_337936_1" annotation="Author:georg.&#xA;Created:30.04.07 17:09.&#xA;Title:.&#xA;Comment:.&#xA;"/>
  <ownedPackage name="base" xmiGuid="_11_5_6340215_1177945847578_658780_128">
    <nestedPackage name="parts" xmiGuid="_11_5_6340215_1178034108625_159847_2">
      <classifier xsi:type="genesezMM:MClass" name="Screw" xmiGuid="_11_5_6340215_1178034133828_951385_16"
          visibility="public">
        <property xsi:type="genesezMM:MAttribute" name="length" xmiGuid="_11_5_6340215_1178034163484_364469_37"
            visibility="private" multiplicity="1" type="example.ecore#//@primitiveTypes.0">
          <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181124278085_474303_310" annotation="describes the length of a screw"/>
        </property>
        <property xsi:type="genesezMM:MAttribute" name="diameter" xmiGuid="_11_5_6340215_1178034174218_253052_39"
            visibility="private" multiplicity="1" type="example.ecore#//@primitiveTypes.0"/>
        <property xsi:type="genesezMM:MAttribute" name="metric" xmiGuid="_11_5_6340215_1178034186171_435038_41"
            visibility="private" multiplicity="1" type="example.ecore#//@primitiveTypes.1"/>
      </classifier>
    </nestedPackage>
    <association name="a1" xmiGuid="_11_5_6340215_1177945988421_850744_191" end="example.ecore#//@ownedPackage.0/@classifier.0/@property.2 example.ecore#//@ownedPackage.0/@classifier.1/@property.2"/>
    <association name="a2" xmiGuid="_11_5_6340215_1178037495031_669688_168" end="example.ecore#//@ownedPackage.0/@classifier.1/@property.3"/>
    <association name="" xmiGuid="_11_5_6340215_1178610607125_702467_4" end="example.ecore#//@ownedPackage.0/@classifier.0/@property.3"/>
    <classifier xsi:type="genesezMM:MClass" name="Car" xmiGuid="_11_5_6340215_1177945913718_872802_139"
        stereotype="example.ecore#//@anyStereotype.0" visibility="public" supertype="example.ecore#//@ownedPackage.0/@classifier.2">
      <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181226127261_132108_445" annotation="A car is a vehicle with four wheels and drives on the road."/>
      <taggedValue value="[testvalue, nextvalue]" tag="example.ecore#//@anyStereotype.0/@property.1"/>
      <taggedValue value="true" tag="example.ecore#//@anyStereotype.0/@property.3"/>
      <taggedValue value="false" tag="example.ecore#//@anyStereotype.0/@property.4"/>
      <operation name="drive" xmiGuid="_11_5_6340215_1179222914421_654419_131" visibility="public"
          final="true" returnType="example.ecore#//@primitiveTypes.1" raisedException="example.ecore#//@ownedPackage.0/@classifier.4 example.ecore#//@ownedPackage.0/@classifier.5">
        <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181226556800_195711_453" annotation="define if the car is driving"/>
        <parameter name="speed" xmiGuid="_11_5_6340215_1179222941718_80142_133" direction="inout"
            type="example.ecore#//@primitiveTypes.3">
          <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181226605036_705503_455" annotation="acutal speed of the car"/>
        </parameter>
      </operation>
      <operation name="Car" xmiGuid="_11_5_6340215_1179229080562_965427_117" visibility="public"
          returnType="example.ecore#//@primitiveTypes.5" raisedException="example.ecore#//@ownedPackage.0/@classifier.5">
        <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181226433345_978623_450" annotation="constructor of the class car"/>
        <parameter name="mxs" xmiGuid="_11_5_6340215_1179229118640_338515_119" direction="inout"
            type="example.ecore#//@primitiveTypes.3">
          <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181226496096_458411_452" annotation="maximum of speed"/>
        </parameter>
        <parameter name="make" xmiGuid="_11_5_6340215_1179229118656_707445_120" direction="inout"
            type="example.ecore#//@primitiveTypes.2">
          <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181226482127_601270_451" annotation="i don't know what make do"/>
        </parameter>
      </operation>
      <property xsi:type="genesezMM:MAttribute" name="MaxSpeed" xmiGuid="_11_5_6340215_1177946061546_878977_243"
          visibility="private" multiplicity="1" type="example.ecore#//@primitiveTypes.3">
        <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181226217638_754786_447" annotation="describs the maximum speed of a car">
          <nestedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181285009203_109401_310"
              annotation="internal bla bla bla"/>
        </ownedComment>
      </property>
      <property xsi:type="genesezMM:MAttribute" name="noOfWheels" xmiGuid="_11_5_6340215_1178786244296_257674_121"
          visibility="private" multiplicity="1" derived="true" type="example.ecore#//@primitiveTypes.4">
        <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181226190575_680255_446" annotation="count the number of wheels"/>
      </property>
      <property xsi:type="genesezMM:MAssociationRole" name="wheels" xmiGuid="_11_5_6340215_1177945988421_623431_192"
          visibility="private" multiplicity="-1" type="example.ecore#//@ownedPackage.0/@classifier.1"
          association="example.ecore#//@ownedPackage.0/@association.0" opposite="example.ecore#//@ownedPackage.0/@classifier.1/@property.2">
        <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181226309358_257289_449" annotation="reference to normal wheels on a car"/>
      </property>
      <property xsi:type="genesezMM:MAssociationRole" name="spare" xmiGuid="_11_5_6340215_1178610607125_74363_5"
          visibility="private" multiplicity="1" type="example.ecore#//@ownedPackage.0/@classifier.1"
          association="example.ecore#//@ownedPackage.0/@association.2">
        <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181226294592_711013_448" annotation="reference to the spared wheel"/>
      </property>
    </classifier>
    <classifier xsi:type="genesezMM:MClass" name="Wheel" xmiGuid="_11_5_6340215_1177945943625_542159_161"
        stereotype="example.ecore#//@anyStereotype.0" visibility="public" supertype="example.ecore#//@ownedPackage.0/@classifier.3">
      <taggedValue value="[blah]" tag="example.ecore#//@anyStereotype.0/@property.1"/>
      <taggedValue value="true" tag="example.ecore#//@anyStereotype.0/@property.3"/>
      <taggedValue value="true" tag="example.ecore#//@anyStereotype.0/@property.4"/>
      <operation name="change" xmiGuid="_11_5_6340215_1179139054625_520706_1" visibility="public"
          returnType="example.ecore#//@primitiveTypes.1">
        <parameter name="newWheel" xmiGuid="_11_5_6340215_1179139099015_142775_3"
            direction="inout" type="example.ecore#//@ownedPackage.0/@classifier.3"/>
      </operation>
      <operation name="roll" xmiGuid="_11_5_6340215_1179238960437_25222_122" visibility="public"
          returnType="example.ecore#//@primitiveTypes.5"/>
      <property xsi:type="genesezMM:MAttribute" name="diameter" xmiGuid="_11_5_6340215_1177945958000_326546_182"
          visibility="private" multiplicity="1" type="example.ecore#//@primitiveTypes.0"/>
      <property xsi:type="genesezMM:MAttribute" name="specification" xmiGuid="_11_5_6340215_1178785354859_924284_117"
          visibility="private" multiplicity="-1" type="example.ecore#//@primitiveTypes.2"/>
      <property xsi:type="genesezMM:MAssociationRole" name="mycar" xmiGuid="_11_5_6340215_1177945988421_335383_193"
          visibility="private" multiplicity="1" type="example.ecore#//@ownedPackage.0/@classifier.0"
          association="example.ecore#//@ownedPackage.0/@association.0" opposite="example.ecore#//@ownedPackage.0/@classifier.0/@property.2"/>
      <property xsi:type="genesezMM:MAssociationRole" name="screw" xmiGuid="_11_5_6340215_1178037495031_331770_169"
          visibility="private" multiplicity="-1" type="example.ecore#//@ownedPackage.0/@nestedPackage.0/@classifier.0"
          association="example.ecore#//@ownedPackage.0/@association.1"/>
    </classifier>
    <classifier xsi:type="genesezMM:MClass" name="Vehicle" xmiGuid="_11_5_6340215_1179139182234_646597_164"
        visibility="public" abstract="true">
      <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181202352886_638468_310" annotation="This abstract class Vehicle is the superclass for all things that can drive (for example: car, boat, air plane, ...).">
        <nestedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181205577224_618441_444" annotation=""/>
      </ownedComment>
      <operation name="drive" xmiGuid="_11_5_6340215_1179222625687_525666_120" visibility="public"
          abstract="true" returnType="example.ecore#//@primitiveTypes.1" raisedException="example.ecore#//@ownedPackage.0/@classifier.4 example.ecore#//@ownedPackage.0/@classifier.5">
        <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181551862765_790518_444" annotation="nothing"/>
        <parameter name="speed" xmiGuid="_11_5_6340215_1179222679562_488094_122" direction="inout"
            type="example.ecore#//@primitiveTypes.3">
          <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1181221129508_173383_310" annotation="define the actual of speed of the vehicle"/>
        </parameter>
      </operation>
      <property xsi:type="genesezMM:MAttribute" name="make" xmiGuid="_11_5_6340215_1177946075218_295795_245"
          visibility="private" multiplicity="1" type="example.ecore#//@primitiveTypes.2"/>
    </classifier>
    <classifier xsi:type="genesezMM:MInterface" name="Changeable" xmiGuid="_11_5_6340215_1179139231828_754744_209"
        visibility="public">
      <operation name="change" xmiGuid="_11_5_6340215_1179139274500_389758_230" visibility="public"
          abstract="true" returnType="example.ecore#//@primitiveTypes.1">
        <parameter name="newInstance" xmiGuid="_11_5_6340215_1179139296515_759109_232"
            direction="inout" type="example.ecore#//@ownedPackage.0/@classifier.3"/>
      </operation>
      <property xsi:type="genesezMM:MAttribute" name="DEFAULT_PERIOD" xmiGuid="_11_5_6340215_1179221622703_154223_1"
          visibility="public" multiplicity="1" type="example.ecore#//@primitiveTypes.4"
          defaultvalue="66" final="true"/>
    </classifier>
    <classifier xsi:type="genesezMM:MClass" name="WhatAMessException" xmiGuid="_11_5_6340215_1179244945187_500153_35"
        visibility="public" supertype="example.ecore#//@ownedPackage.1/@nestedPackage.0/@classifier.0"/>
    <classifier xsi:type="genesezMM:MClass" name="NotReallySeriousException" xmiGuid="_11_5_6340215_1179244974031_673010_60"
        visibility="public" supertype="example.ecore#//@ownedPackage.1/@nestedPackage.0/@classifier.0">
      <ownedComment xmiGuid="_12_5EAPbeta2_8a7027a_1180697939865_862590_312" annotation="this is a comment&#xA;this is the second comment"/>
    </classifier>
  </ownedPackage>
  <ownedPackage name="java" xmiGuid="_11_5_6340215_1180026884515_618369_2">
    <nestedPackage name="util" xmiGuid="_11_5_6340215_1180026900046_168093_13">
      <classifier xsi:type="genesezMM:MClass" name="Exception" xmiGuid="_11_5_6340215_1180026912875_354576_27"
          visibility="public"/>
    </nestedPackage>
  </ownedPackage>
  <primitiveTypes name="float" xmiGuid="float"/>
  <primitiveTypes name="Boolean" xmiGuid="Boolean"/>
  <primitiveTypes name="String" xmiGuid="String"/>
  <primitiveTypes name="int" xmiGuid="int"/>
  <primitiveTypes name="Integer" xmiGuid="Integer"/>
  <primitiveTypes name="void" xmiGuid="void"/>
  <anyStereotype name="hasAspects" xmiGuid="_12_5_6340215_1181586884437_492992_565">
    <property name="aspect" type="genesezMM.impl.MPrimitiveTypeImpl@1cea971 (name: String, xmiGuid: String) (visibility: null, abstract: false, final: false)"/>
    <property name="tv2" type="genesezMM.impl.MPrimitiveTypeImpl@1cea971 (name: String, xmiGuid: String) (visibility: null, abstract: false, final: false)"/>
    <property name="base_Class" type="genesezMM.impl.MClassImpl@404991 (name: Class, xmiGuid: Class) (visibility: public, abstract: false, final: false)"/>
    <property name="persist" type="genesezMM.impl.MPrimitiveTypeImpl@1bd871 (name: Boolean, xmiGuid: Boolean) (visibility: null, abstract: false, final: false)"/>
    <property name="showThis" type="genesezMM.impl.MPrimitiveTypeImpl@1bd871 (name: Boolean, xmiGuid: Boolean) (visibility: null, abstract: false, final: false)"/>
  </anyStereotype>
</genesezMM:MModel>
