<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="genesezMM"
    nsURI="/genesezMM/genesezMM" nsPrefix="genesezMM">
  <eClassifiers xsi:type="ecore:EClass" name="MPackage" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedPackage" upperBound="-1"
        eType="#//MPackage" containment="true" eOpposite="#//MPackage/nestingPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestingPackage" eType="#//MPackage"
        eOpposite="#//MPackage/nestedPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//MModel"
        eOpposite="#//MModel/ownedPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
        eType="#//MAssociation" containment="true" eOpposite="#//MAssociation/owningPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" upperBound="-1"
        eType="#//MClassifier" containment="true" eOpposite="#//MClassifier/owningPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MClass" eSuperTypes="#//MClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAssociation" eType="#//MAssociation"
        eOpposite="#//MAssociation/associationClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAssociationRole" eSuperTypes="#//MProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="composition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" lowerBound="1"
        eType="#//MAssociation" eOpposite="#//MAssociation/end"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" lowerBound="1"
        eType="#//MAssociationRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAssociation" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" upperBound="-1"
        eType="#//MAssociationRole" eOpposite="#//MAssociationRole/association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningPackage" lowerBound="1"
        eType="#//MPackage" eOpposite="#//MPackage/association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationClass" eType="#//MClass"
        eOpposite="#//MClass/ownedAssociation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAttribute" eSuperTypes="#//MElement #//MProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultvalue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MModel" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPackage" upperBound="-1"
        eType="#//MPackage" containment="true" eOpposite="#//MPackage/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveTypes" upperBound="-1"
        eType="#//MPrimitiveType" containment="true" eOpposite="#//MPrimitiveType/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anyStereotype" upperBound="-1"
        eType="#//MStereotype" containment="true" eOpposite="#//MStereotype/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmiGuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" upperBound="-1"
        eType="#//MStereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" upperBound="-1"
        eType="#//MComment" containment="true" eOpposite="#//MComment/owningElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MProperty" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//MClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
        eType="#//MClassifier" eOpposite="#//MClassifier/property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MInterface" eSuperTypes="#//MClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="MClassifier" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningPackage" lowerBound="1"
        eType="#//MPackage" eOpposite="#//MPackage/classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" upperBound="-1"
        eType="#//MClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
        eType="#//MOperation" containment="true" eOpposite="#//MOperation/classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="#//MProperty" containment="true" eOpposite="#//MProperty/classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOperation" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//MParameter" containment="true" eOpposite="#//MParameter/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
        eType="#//MClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raisedException" upperBound="-1"
        eType="#//MClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
        eType="#//MClassifier" eOpposite="#//MClassifier/operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MParameter" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultvalue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//MOperation" eOpposite="#//MOperation/parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//MClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDataType" eSuperTypes="#//MClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="MPrimitiveType" eSuperTypes="#//MDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//MModel"
        eOpposite="#//MModel/primitiveTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEnumeration" eSuperTypes="#//MDataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="MStereotype" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValue" upperBound="-1"
        eType="#//MTaggedValue" containment="true" eOpposite="#//MTaggedValue/owningStereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//MModel"
        eOpposite="#//MModel/anyStereotype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTaggedValue" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningStereotype" lowerBound="1"
        eType="#//MStereotype" eOpposite="#//MStereotype/taggedValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MComment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmiGuid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningElement" lowerBound="1"
        eType="#//MElement" eOpposite="#//MElement/ownedComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedComment" upperBound="-1"
        eType="#//MComment" containment="true" eOpposite="#//MComment/nestingComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestingComment" eType="#//MComment"
        eOpposite="#//MComment/nestedComment"/>
  </eClassifiers>
</ecore:EPackage>
