<?xml version="1.0" encoding="UTF-8"?>
<codegenMm:MModel xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:codegenMm="http://www.genesez.de/codegenMm" name="sampleCodegen">
  <ownedPackage name="base">
    <class name="Car">
      <attribute type="org.eclipse.uml2.uml.internal.impl.ClassImpl@f8395f (name: Wheel, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false) (isActive: false, isAbstract: false)"
          visibility="private" name="wheels"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@170b890 (name: int, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="maxSpeed"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@c26acd (name: String, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="make"/>
    </class>
    <class name="Wheel">
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@812051 (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="diameter"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.ClassImpl@6c1a82 (name: Car, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false) (isActive: false, isAbstract: false)"
          visibility="private" name="car"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.ClassImpl@b51c29 (name: Screw, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false) (isActive: false, isAbstract: false)"
          visibility="private" name="fixing"/>
    </class>
    <nestedPackage name="parts">
      <class name="Screw">
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@812051 (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="length"/>
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@812051 (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="diameter"/>
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@1a0a87c (name: Boolean, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="metric"/>
      </class>
    </nestedPackage>
    <association name="Association"/>
    <association name="Association"/>
  </ownedPackage>
</codegenMm:MModel>
