<?xml version="1.0" encoding="UTF-8"?>
<codegenMm:MModel xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:codegenMm="http://www.genesez.de/codegenMm" name="sampleCodegen">
  <ownedPackage name="base">
    <class name="Car">
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@bd630e (name: int, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="maxSpeed"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@b3f93c (name: String, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="make"/>
    </class>
    <class name="Wheel">
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@44a541 (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="diameter"/>
    </class>
    <nestedPackage name="parts">
      <class name="Screw">
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@44a541 (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="length"/>
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@44a541 (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="diameter"/>
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@1a10f82 (name: Boolean, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="metric"/>
      </class>
    </nestedPackage>
    <association name="a1">
      <end name="wheels"/>
      <end name="mycar"/>
    </association>
    <association name="a2">
      <end name="screw"/>
      <end name="fixing"/>
    </association>
    <association name="spareWheel">
      <end name="spare"/>
      <end name="owner"/>
    </association>
  </ownedPackage>
</codegenMm:MModel>
