<?xml version="1.0" encoding="UTF-8"?>
<codegenMm:MModel xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:codegenMm="http://www.genesez.de/codegenMm" name="sampleCodegen">
  <ownedPackage name="base">
    <class name="Car">
      <attribute type="org.eclipse.uml2.uml.internal.impl.ClassImpl@7e9ce2 (name: Wheel, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false) (isActive: false, isAbstract: false)"
          visibility="private" name="wheels"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@a5d82a (name: int, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="maxSpeed"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@182237d (name: String, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="make"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.ClassImpl@7e9ce2 (name: Wheel, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false) (isActive: false, isAbstract: false)"
          visibility="private" name="spare"/>
    </class>
    <class name="Wheel">
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@a4b9da (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="diameter"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.ClassImpl@6c1a82 (name: Car, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false) (isActive: false, isAbstract: false)"
          visibility="private" name="mycar"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.ClassImpl@d1e7c2 (name: Screw, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false) (isActive: false, isAbstract: false)"
          visibility="private" name="fixing"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.ClassImpl@6c1a82 (name: Car, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false) (isActive: false, isAbstract: false)"
          visibility="private" name="owner"/>
    </class>
    <nestedPackage name="parts">
      <class name="Screw">
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@a4b9da (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="length"/>
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@a4b9da (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="diameter"/>
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@666c7a (name: Boolean, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="metric"/>
      </class>
    </nestedPackage>
    <association name="wheelsmycar"/>
    <association name="nullfixing"/>
    <association name="spareWheel"/>
  </ownedPackage>
</codegenMm:MModel>
