<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="de.genesez.metamodel"
    nsURI="platform:/plugin/de.genesez.metamodel/model-gen/genesezMM.ecore" nsPrefix="de.genesez.metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="MPackage" eSuperTypes="genesezMM.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedPackage" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MPackage" containment="true" eOpposite="genesezMM.ecore#//MPackage/nestingPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestingPackage" eType="ecore:EClass genesezMM.ecore#//MPackage"
        changeable="false" eOpposite="genesezMM.ecore#//MPackage/nestedPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MAssociation" containment="true" eOpposite="genesezMM.ecore#//MAssociation/owningPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MClassifier" containment="true" eOpposite="genesezMM.ecore#//MClassifier/owningPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MClass" eSuperTypes="genesezMM.ecore#//MClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAssociation" eType="ecore:EClass genesezMM.ecore#//MAssociation"
        eOpposite="genesezMM.ecore#//MAssociation/associationClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAssociationRole" eSuperTypes="genesezMM.ecore#//MProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="composition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MAssociation" eOpposite="genesezMM.ecore#//MAssociation/end"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MAssociationRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAssociation" eSuperTypes="genesezMM.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MAssociationRole" eOpposite="genesezMM.ecore#//MAssociationRole/association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningPackage" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MPackage" changeable="false" eOpposite="genesezMM.ecore#//MPackage/association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationClass" eType="ecore:EClass genesezMM.ecore#//MClass"
        eOpposite="genesezMM.ecore#//MClass/ownedAssociation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAttribute" eSuperTypes="genesezMM.ecore#//MProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultvalue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MModel" eSuperTypes="genesezMM.ecore#//MPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveTypes" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MPrimitiveType" containment="true" eOpposite="genesezMM.ecore#//MPrimitiveType/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anyStereotype" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MStereotype" containment="true" eOpposite="genesezMM.ecore#//MStereotype/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalTypes" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MExternal" containment="true" eOpposite="genesezMM.ecore#//MExternal/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmiGuid" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MComment" containment="true" eOpposite="genesezMM.ecore#//MComment/owningElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValue" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MTaggedValue" containment="true" eOpposite="genesezMM.ecore#//MTaggedValue/owningElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MStereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspect" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MAspect" containment="true" eOpposite="genesezMM.ecore#//MAspect/element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MProperty" eSuperTypes="genesezMM.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MClassifier" changeable="false" eOpposite="genesezMM.ecore#//MClassifier/property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericRealization" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MGeneric" containment="true" eOpposite="genesezMM.ecore#//MGeneric/owningProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass genesezMM.ecore#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MInterface" eSuperTypes="genesezMM.ecore#//MClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="MClassifier" abstract="true" eSuperTypes="genesezMM.ecore#//MElement genesezMM.ecore#//MType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningPackage" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MPackage" changeable="false" eOpposite="genesezMM.ecore#//MPackage/classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MOperation" containment="true" eOpposite="genesezMM.ecore#//MOperation/classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MProperty" containment="true" eOpposite="genesezMM.ecore#//MProperty/classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericParameter" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MGeneric" containment="true" eOpposite="genesezMM.ecore#//MGeneric/owningClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realization" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOperation" eSuperTypes="genesezMM.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MParameter" containment="true" eOpposite="genesezMM.ecore#//MParameter/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MClassifier" changeable="false" eOpposite="genesezMM.ecore#//MClassifier/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericParameter" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MGeneric" containment="true" eOpposite="genesezMM.ecore#//MGeneric/owningOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raisedException" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MParameter" eSuperTypes="genesezMM.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultvalue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MOperation" changeable="false" eOpposite="genesezMM.ecore#//MOperation/parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericRealization" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MGeneric" containment="true" eOpposite="genesezMM.ecore#//MGeneric/owningParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass genesezMM.ecore#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDataType" eSuperTypes="genesezMM.ecore#//MClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="MPrimitiveType" eSuperTypes="genesezMM.ecore#//MType genesezMM.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="ecore:EClass genesezMM.ecore#//MModel"
        changeable="false" eOpposite="genesezMM.ecore#//MModel/primitiveTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEnumeration" eSuperTypes="genesezMM.ecore#//MDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MLiteral" containment="true" eOpposite="genesezMM.ecore#//MLiteral/owningEnumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MStereotype" eSuperTypes="genesezMM.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MTag" containment="true" eOpposite="genesezMM.ecore#//MTag/stereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="ecore:EClass genesezMM.ecore#//MModel"
        changeable="false" eOpposite="genesezMM.ecore#//MModel/anyStereotype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MStereotype" changeable="false" eOpposite="genesezMM.ecore#//MStereotype/property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MComment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmiGuid" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningElement" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MElement" changeable="false" eOpposite="genesezMM.ecore#//MElement/ownedComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedComment" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MComment" containment="true" eOpposite="genesezMM.ecore#//MComment/nestingComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestingComment" eType="ecore:EClass genesezMM.ecore#//MComment"
        changeable="false" eOpposite="genesezMM.ecore#//MComment/nestedComment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTaggedValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningElement" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MElement" changeable="false" eOpposite="genesezMM.ecore#//MElement/taggedValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tag" lowerBound="1" eType="ecore:EClass genesezMM.ecore#//MTag"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAspect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MElement" changeable="false" eOpposite="genesezMM.ecore#//MElement/aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="introduction" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MIntroduction" containment="true" eOpposite="genesezMM.ecore#//MIntroduction/origin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pointcut" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MPointcut" containment="true" eOpposite="genesezMM.ecore#//MPointcut/origin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MIntroduction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MAspect" changeable="false" eOpposite="genesezMM.ecore#//MAspect/introduction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MPointcut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" lowerBound="1"
        eType="ecore:EEnum genesezMM.ecore#//MDestinationKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MAspect" changeable="false" eOpposite="genesezMM.ecore#//MAspect/pointcut"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLiteral" eSuperTypes="genesezMM.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningEnumeration" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MEnumeration" changeable="false" eOpposite="genesezMM.ecore#//MEnumeration/literal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MGeneric" eSuperTypes="genesezMM.ecore#//MType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningClassifier" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MClassifier" changeable="false" eOpposite="genesezMM.ecore#//MClassifier/genericParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningOperation" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MOperation" changeable="false" eOpposite="genesezMM.ecore#//MOperation/genericParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningProperty" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MProperty" changeable="false" eOpposite="genesezMM.ecore#//MProperty/genericRealization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningParameter" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MParameter" changeable="false" eOpposite="genesezMM.ecore#//MParameter/genericRealization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningExternal" lowerBound="1"
        eType="ecore:EClass genesezMM.ecore#//MExternal" changeable="false" eOpposite="genesezMM.ecore#//MExternal/genericParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MExternal" eSuperTypes="genesezMM.ecore#//MType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="ecore:EClass genesezMM.ecore#//MModel"
        changeable="false" eOpposite="genesezMM.ecore#//MModel/externalTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericParameter" upperBound="-1"
        eType="ecore:EClass genesezMM.ecore#//MGeneric" containment="true" eOpposite="genesezMM.ecore#//MGeneric/owningExternal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MDestinationKind">
    <eLiterals name="onEntry" value="1"/>
    <eLiterals name="onExit" value="2"/>
    <eLiterals name="onException" value="3"/>
    <eLiterals name="around" value="4"/>
    <eLiterals name="external" value="5"/>
  </eClassifiers>
</ecore:EPackage>
