<?xml version="1.0" encoding="UTF-8"?>
<codegenMm:MModel xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:codegenMm="http://www.genesez.de/codegenMm" name="sampleCodegen"
    xmiId="_MZauNP2EEdueEZtrjix5tA">
  <ownedPackage name="base" xmiId="_MZauPv2EEdueEZtrjix5tA">
    <class name="Car" xmiId="_MZauP_2EEdueEZtrjix5tA">
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@1d1282d (name: int, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="maxSpeed" xmiId="_MZauQ_2EEdueEZtrjix5tA"/>
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@5bcf3a (name: String, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="make" xmiId="_MZauRP2EEdueEZtrjix5tA"/>
    </class>
    <class name="Wheel" xmiId="_MZauRv2EEdueEZtrjix5tA">
      <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@5acf13 (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
          visibility="private" name="diameter" xmiId="_MZauR_2EEdueEZtrjix5tA"/>
    </class>
    <nestedPackage name="parts" xmiId="_MZauUP2EEdueEZtrjix5tA">
      <class name="Screw" xmiId="_MZauUf2EEdueEZtrjix5tA">
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@5acf13 (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="length" xmiId="_MZauUv2EEdueEZtrjix5tA"/>
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@5acf13 (name: float, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="diameter" xmiId="_MZauU_2EEdueEZtrjix5tA"/>
        <attribute type="org.eclipse.uml2.uml.internal.impl.PrimitiveTypeImpl@1bf7435 (name: Boolean, visibility: &lt;unset>) (isLeaf: false, visibility: public, isAbstract: false)"
            visibility="private" name="metric" xmiId="_MZauVP2EEdueEZtrjix5tA"/>
      </class>
    </nestedPackage>
  </ownedPackage>
</codegenMm:MModel>
