/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package genesezMM.validation;

import genesezMM.MPackage;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link genesezMM.MClassifier}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MClassifierValidator
{
  boolean validate();

  boolean validateVisibility(String value);
  boolean validateAbstract(boolean value);
  boolean validateFinal(boolean value);
  boolean validateOwningPackage(MPackage value);
  boolean validateOperation(EList value);
  boolean validateProperty(EList value);
  boolean validateGenericParameter(EList value);
  boolean validateSupertype(EList value);
  boolean validateRealization(EList value);
  boolean validateGeneralization(EList value);
  boolean validateSupplier(EList value);
}
