/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package genesezMM.validation;

import genesezMM.MModel;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link genesezMM.MExternal}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MExternalValidator
{
  boolean validate();

  boolean validateSpecification(String value);
  boolean validateModel(MModel value);
  boolean validateGenericParameter(EList value);
}
