/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package genesezMM.validation;

import genesezMM.MAspect;

/**
 * A sample validator interface for {@link genesezMM.MIntroduction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MIntroductionValidator
{
  boolean validate();

  boolean validateDomain(String value);
  boolean validateName(String value);
  boolean validateOrigin(MAspect value);
}
