/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package genesezMM.validation;

import genesezMM.MClassifier;
import genesezMM.MType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link genesezMM.MOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MOperationValidator
{
  boolean validate();

  boolean validateVisibility(String value);
  boolean validateStatic(boolean value);
  boolean validateAbstract(boolean value);
  boolean validateFinal(boolean value);
  boolean validateMultiplicity(int value);
  boolean validateUnique(boolean value);
  boolean validateOrdered(boolean value);
  boolean validateParameter(EList value);
  boolean validateClassifier(MClassifier value);
  boolean validateGenericParameter(EList value);
  boolean validateRaisedException(EList value);
  boolean validateReturnType(MType value);
}
