/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.genesez.metamodel.genesezMM.validation;

import de.genesez.metamodel.genesezMM.MElement;
import de.genesez.metamodel.genesezMM.MTag;

/**
 * A sample validator interface for {@link de.genesez.metamodel.genesezMM.MTaggedValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MTaggedValueValidator
{
  boolean validate();

  boolean validateValue(String value);
  boolean validateOwningElement(MElement value);
  boolean validateTag(MTag value);
}
