//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.02 at 11:09:44 PM MEZ 
//


package de.genesez.platforms.common.typemapping.types;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for typeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://www.genesez.de/typemapping}to"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.genesez.de/typemapping}context" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="from" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeType", propOrder = {
    "destinationMapping",
    "contextMap"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2009-03-02T11:09:44+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-646")
public class SingleValuedType {

    @XmlElement(name = "to")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2009-03-02T11:09:44+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-646")
    protected String destinationMapping;
    @XmlElement(name = "context")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2009-03-02T11:09:44+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-646")
    protected List<Context> contextMap;
    @XmlAttribute(name = "from", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2009-03-02T11:09:44+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-646")
    protected String sourceMapping;

    /**
     * Gets the value of the destinationMapping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2009-03-02T11:09:44+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-646")
    public String getDestinationMapping() {
        return destinationMapping;
    }

    /**
     * Sets the value of the destinationMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2009-03-02T11:09:44+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-646")
    public void setDestinationMapping(String value) {
        this.destinationMapping = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2009-03-02T11:09:44+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-646")
    public boolean isSetDestinationMapping() {
        return (this.destinationMapping!= null);
    }

    /**
     * Gets the value of the contextMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Context }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2009-03-02T11:09:44+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-646")
    public List<Context> getContextMap() {
        if (contextMap == null) {
            contextMap = new ArrayList<Context>();
        }
        return this.contextMap;
    }

    /**
     * Gets the value of the sourceMapping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2009-03-02T11:09:44+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-646")
    public String getSourceMapping() {
        return sourceMapping;
    }

    /**
     * Sets the value of the sourceMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2009-03-02T11:09:44+01:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-646")
    public void setSourceMapping(String value) {
        this.sourceMapping = value;
    }

}
