//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.25 at 01:44:42 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.genesez.de/typemapping", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.genesez.platforms.common.typemapping.types;
