<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDDM_Object extends Doctrine_Record
{

	public function setTableDefinition()
	{
		$this->setTableName('ddm_object');

		$this->hasColumn('o_class', 'integer', null);
	}

	public function setUp()
	{
		parent::setUp();
		$this->hasOne('DDM_Class as class', array('local' => 'o_class',
			'foreign' => 'id',
			'onDelete' => 'RESTRICT'));
	}

}
