<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDDM_Attribute extends Doctrine_Record
{

	public function setTableDefinition()
	{
		$this->setTableName('ddm_attribute');

		$this->hasColumn('a_class', 'integer', null);
		$this->hasColumn('a_type', 'integer', null);
		$this->hasColumn('a_name', 'string', 1024, array('notnull' => true));
		$this->hasColumn('a_column', 'string', 1024, array('notnull' => true));
		$this->hasColumn('a_description', 'string', 255, array('notnull' => true));
	}

	public function setUp()
	{
		parent::setUp();
		$this->hasOne('DDM_Class as class', array('local' => 'a_class',
			'foreign' => 'id',
			'onDelete' => 'CASCADE'));

		$this->hasOne('DDM_Type as type', array('local' => 'a_type',
			'foreign' => 'id',
			'onDelete' => 'RESTRICT'));
	}

}
