<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gcore" nsURI="http://genesez.org/metamodel/core" nsPrefix="gcore">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Author:gerbe.Created:8/30/12 6:57 PM.Title:.Comment:."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MPackage" eSuperTypes="gcore.ecore#//MDefinitionContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestingPackage" eType="ecore:EClass gcore.ecore#//MPackage"
        changeable="false" eOpposite="gcore.ecore#//MPackage/nestedPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedPackage" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MPackage" containment="true" eOpposite="gcore.ecore#//MPackage/nestingPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MAssociation" containment="true" eOpposite="gcore.ecore#//MAssociation/owningPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MClass" eSuperTypes="gcore.ecore#//MClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAssociation" eType="ecore:EClass gcore.ecore#//MAssociation"
        eOpposite="gcore.ecore#//MAssociation/associationClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAssociationRole" eSuperTypes="gcore.ecore#//MProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="composition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oppositeLowerBoundMultiplicity"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oppositeUpperBoundMultiplicity"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifierMultiplicity"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MAssociation" eOpposite="gcore.ecore#//MAssociation/end"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MAssociationRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAssociation" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MAssociationRole" eOpposite="gcore.ecore#//MAssociationRole/association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningPackage" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MPackage" changeable="false" eOpposite="gcore.ecore#//MPackage/association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationClass" eType="ecore:EClass gcore.ecore#//MClass"
        eOpposite="gcore.ecore#//MClass/ownedAssociation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAttribute" eSuperTypes="gcore.ecore#//MProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultvalue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MModel" eSuperTypes="gcore.ecore#//MPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anyStereotype" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MStereotype" containment="true" eOpposite="gcore.ecore#//MStereotype/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalTypes" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MExternal" containment="true" eOpposite="gcore.ecore#//MExternal/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmiGuid" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MComment" containment="true" eOpposite="gcore.ecore#//MComment/owningElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValue" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MTaggedValue" containment="true" eOpposite="gcore.ecore#//MTaggedValue/owningElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MStereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspect" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MAspect" containment="true" eOpposite="gcore.ecore#//MAspect/element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MProperty" abstract="true" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBoundMultiplicity"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBoundMultiplicity"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MClassifier" changeable="false" eOpposite="gcore.ecore#//MClassifier/property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericRealization" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MGeneric" containment="true" eOpposite="gcore.ecore#//MGeneric/owningProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass gcore.ecore#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MInterface" eSuperTypes="gcore.ecore#//MClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="MClassifier" abstract="true" eSuperTypes="gcore.ecore#//MElement gcore.ecore#//MType gcore.ecore#//MDefinitionContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MOperation" containment="true" eOpposite="gcore.ecore#//MOperation/classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MProperty" containment="true" eOpposite="gcore.ecore#//MProperty/classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericParameter" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MGeneric" containment="true" eOpposite="gcore.ecore#//MGeneric/owningClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realization" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MType" eOpposite="gcore.ecore#//MType/specialization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningContext" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MDefinitionContext" changeable="false" eOpposite="gcore.ecore#//MDefinitionContext/classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOperation" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MClassifier" changeable="false" eOpposite="gcore.ecore#//MClassifier/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericParameter" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MGeneric" containment="true" eOpposite="gcore.ecore#//MGeneric/owningOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raisedException" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" eType="ecore:EClass gcore.ecore#//MParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MParameter" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultvalue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBoundMultiplicity"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBoundMultiplicity"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericRealization" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MGeneric" containment="true" eOpposite="gcore.ecore#//MGeneric/owningParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass gcore.ecore#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="ecore:EClass gcore.ecore#//MEvent"
        changeable="false" eOpposite="gcore.ecore#//MEvent/parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDataType" eSuperTypes="gcore.ecore#//MClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="MEnumeration" eSuperTypes="gcore.ecore#//MDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MLiteral" containment="true" eOpposite="gcore.ecore#//MLiteral/owningEnumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MStereotype" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MTag" containment="true" eOpposite="gcore.ecore#//MTag/stereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="ecore:EClass gcore.ecore#//MModel"
        changeable="false" eOpposite="gcore.ecore#//MModel/anyStereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MStereotype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MStereotype" changeable="false" eOpposite="gcore.ecore#//MStereotype/property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MComment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmiGuid" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningElement" eType="ecore:EClass gcore.ecore#//MElement"
        changeable="false" eOpposite="gcore.ecore#//MElement/ownedComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedComment" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MComment" containment="true" eOpposite="gcore.ecore#//MComment/nestingComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestingComment" eType="ecore:EClass gcore.ecore#//MComment"
        changeable="false" eOpposite="gcore.ecore#//MComment/nestedComment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTaggedValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningElement" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MElement" changeable="false" eOpposite="gcore.ecore#//MElement/taggedValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tag" lowerBound="1" eType="ecore:EClass gcore.ecore#//MTag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueReference" eType="ecore:EClass gcore.ecore#//MElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAspect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MElement" changeable="false" eOpposite="gcore.ecore#//MElement/aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="introduction" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MIntroduction" containment="true" eOpposite="gcore.ecore#//MIntroduction/origin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pointcut" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MPointcut" containment="true" eOpposite="gcore.ecore#//MPointcut/origin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MIntroduction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MAspect" changeable="false" eOpposite="gcore.ecore#//MAspect/introduction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MPointcut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" lowerBound="1"
        eType="ecore:EEnum gcore.ecore#//MDestinationKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MAspect" changeable="false" eOpposite="gcore.ecore#//MAspect/pointcut"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLiteral" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningEnumeration" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MEnumeration" changeable="false" eOpposite="gcore.ecore#//MEnumeration/literal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MGeneric" eSuperTypes="gcore.ecore#//MType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningClassifier" eType="ecore:EClass gcore.ecore#//MClassifier"
        changeable="false" eOpposite="gcore.ecore#//MClassifier/genericParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningOperation" eType="ecore:EClass gcore.ecore#//MOperation"
        changeable="false" eOpposite="gcore.ecore#//MOperation/genericParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningProperty" eType="ecore:EClass gcore.ecore#//MProperty"
        changeable="false" eOpposite="gcore.ecore#//MProperty/genericRealization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningParameter" eType="ecore:EClass gcore.ecore#//MParameter"
        changeable="false" eOpposite="gcore.ecore#//MParameter/genericRealization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningExternal" eType="ecore:EClass gcore.ecore#//MExternal"
        changeable="false" eOpposite="gcore.ecore#//MExternal/genericParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="ecore:EClass gcore.ecore#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialization" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MClassifier" eOpposite="gcore.ecore#//MClassifier/generalization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MExternal" eSuperTypes="gcore.ecore#//MType gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="ecore:EClass gcore.ecore#//MModel"
        changeable="false" eOpposite="gcore.ecore#//MModel/externalTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericParameter" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MGeneric" containment="true" eOpposite="gcore.ecore#//MGeneric/owningExternal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MActivity" eSuperTypes="gcore.ecore#//MBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" upperBound="-1" eType="ecore:EClass gcore.ecore#//MFlow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="ecore:EClass gcore.ecore#//MNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAction" eSuperTypes="gcore.ecore#//MNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="ecore:EClass gcore.ecore#//MBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" upperBound="-1" eType="ecore:EClass gcore.ecore#//MClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" upperBound="-1" eType="ecore:EClass gcore.ecore#//MClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass gcore.ecore#//MOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MBehavior" abstract="true" eSuperTypes="gcore.ecore#//MElement gcore.ecore#//MDefinitionContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningContext" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MDefinitionContext" changeable="false" eOpposite="gcore.ecore#//MDefinitionContext/ownedBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MTransition" eOpposite="gcore.ecore#//MTransition/action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MState" eOpposite="gcore.ecore#//MState/entry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" upperBound="-1" eType="ecore:EClass gcore.ecore#//MState"
        eOpposite="gcore.ecore#//MState/exit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="do" upperBound="-1" eType="ecore:EClass gcore.ecore#//MState"
        eOpposite="gcore.ecore#//MState/do"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MStateMachine" eSuperTypes="gcore.ecore#//MBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="smstate" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MState" containment="true" eOpposite="gcore.ecore#//MState/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="smtransition" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MTransition" containment="true" eOpposite="gcore.ecore#//MTransition/statemachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atomicTransition" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MAtomicTransition" containment="true" eOpposite="gcore.ecore#//MAtomicTransition/statemachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MFlow" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MNode" eOpposite="gcore.ecore#//MNode/to"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MNode" eOpposite="gcore.ecore#//MNode/from"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass gcore.ecore#//MGuard"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transport" eType="ecore:EClass gcore.ecore#//MClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MNode" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" upperBound="-1" eType="ecore:EClass gcore.ecore#//MFlow"
        eOpposite="gcore.ecore#//MFlow/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" upperBound="-1" eType="ecore:EClass gcore.ecore#//MFlow"
        eOpposite="gcore.ecore#//MFlow/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MGuard" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" lowerBound="1"
        upperBound="-1" eType="ecore:EClass gcore.ecore#//MTransition" eOpposite="gcore.ecore#//MTransition/guard"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningContext" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MDefinitionContext" changeable="false" eOpposite="gcore.ecore#//MDefinitionContext/guard"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MUseCase" eSuperTypes="gcore.ecore#//MClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="MInitial" eSuperTypes="gcore.ecore#//MNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="MFinal" eSuperTypes="gcore.ecore#//MNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="MState" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="ecore:EClass gcore.ecore#//MStateMachine"
        changeable="false" eOpposite="gcore.ecore#//MStateMachine/smstate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MTransition" eOpposite="gcore.ecore#//MTransition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MTransition" eOpposite="gcore.ecore#//MTransition/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="ecore:EClass gcore.ecore#//MBehavior"
        eOpposite="gcore.ecore#//MBehavior/entry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" eType="ecore:EClass gcore.ecore#//MBehavior"
        eOpposite="gcore.ecore#//MBehavior/exit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="do" eType="ecore:EClass gcore.ecore#//MBehavior"
        eOpposite="gcore.ecore#//MBehavior/do"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superstate" eType="ecore:EClass gcore.ecore#//MCompositeState"
        eOpposite="gcore.ecore#//MCompositeState/substate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTransition" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MState" eOpposite="gcore.ecore#//MState/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MState" eOpposite="gcore.ecore#//MState/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass gcore.ecore#//MGuard"
        eOpposite="gcore.ecore#//MGuard/transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statemachine" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MStateMachine" changeable="false" eOpposite="gcore.ecore#//MStateMachine/smtransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="ecore:EClass gcore.ecore#//MBehavior"
        eOpposite="gcore.ecore#//MBehavior/transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDefinitionContext" abstract="true"
      eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MClassifier" containment="true" eOpposite="gcore.ecore#//MClassifier/owningContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBehavior" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MBehavior" containment="true" eOpposite="gcore.ecore#//MBehavior/owningContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MGuard" containment="true" eOpposite="gcore.ecore#//MGuard/owningContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MEvent" containment="true" eOpposite="gcore.ecore#//MEvent/owningContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEvent" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCall" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isChange" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningContext" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MDefinitionContext" changeable="false" eOpposite="gcore.ecore#//MDefinitionContext/event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MParameter" containment="true" eOpposite="gcore.ecore#//MParameter/event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAtomicTransition" eSuperTypes="gcore.ecore#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definingTransition" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endDo" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" upperBound="-1" eType="ecore:EClass gcore.ecore#//MBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startDo" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="historyContext" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MHistoryState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statemachine" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MStateMachine" changeable="false" eOpposite="gcore.ecore#//MStateMachine/atomicTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startTimer" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MTimeEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stopTimer" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MTimeEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MLeafState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass gcore.ecore#//MLeafState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLeafState" eSuperTypes="gcore.ecore#//MState"/>
  <eClassifiers xsi:type="ecore:EClass" name="MCompositeState" eSuperTypes="gcore.ecore#//MState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="substate" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MState" eOpposite="gcore.ecore#//MState/superstate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MInitialState" eSuperTypes="gcore.ecore#//MLeafState"/>
  <eClassifiers xsi:type="ecore:EClass" name="MFinalState" eSuperTypes="gcore.ecore#//MLeafState"/>
  <eClassifiers xsi:type="ecore:EClass" name="MHistoryState" eSuperTypes="gcore.ecore#//MLeafState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deep" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reachableHistory" upperBound="-1"
        eType="ecore:EClass gcore.ecore#//MLeafState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultHistory" eType="ecore:EClass gcore.ecore#//MLeafState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTimeEvent" eSuperTypes="gcore.ecore#//MEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRelative" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="when" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MDestinationKind">
    <eLiterals name="onEntry" value="1"/>
    <eLiterals name="onExit" value="2"/>
    <eLiterals name="onException" value="3"/>
    <eLiterals name="around" value="4"/>
    <eLiterals name="external" value="5"/>
  </eClassifiers>
</ecore:EPackage>
