<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="genesezMM"
    nsURI="platform:/plugin/de.genesez.metamodel/model-gen/genesezMM.ecore" nsPrefix="genesezMM">
  <eClassifiers xsi:type="ecore:EClass" name="MPackage" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestingPackage" eType="#//MPackage"
        changeable="false" eOpposite="#//MPackage/nestedPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedPackage" upperBound="-1"
        eType="#//MPackage" containment="true" eOpposite="#//MPackage/nestingPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
        eType="#//MAssociation" containment="true" eOpposite="#//MAssociation/owningPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" upperBound="-1"
        eType="#//MClassifier" containment="true" eOpposite="#//MClassifier/owningPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MClass" eSuperTypes="#//MClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAssociation" eType="#//MAssociation"
        eOpposite="#//MAssociation/associationClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAssociationRole" eSuperTypes="#//MProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="composition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" lowerBound="1"
        eType="#//MAssociation" eOpposite="#//MAssociation/end"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" lowerBound="1"
        eType="#//MAssociationRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAssociation" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" upperBound="-1"
        eType="#//MAssociationRole" eOpposite="#//MAssociationRole/association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningPackage" lowerBound="1"
        eType="#//MPackage" changeable="false" eOpposite="#//MPackage/association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associationClass" eType="#//MClass"
        eOpposite="#//MClass/ownedAssociation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAttribute" eSuperTypes="#//MProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultvalue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MModel" eSuperTypes="#//MPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveTypes" upperBound="-1"
        eType="#//MPrimitiveType" containment="true" eOpposite="#//MPrimitiveType/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anyStereotype" upperBound="-1"
        eType="#//MStereotype" containment="true" eOpposite="#//MStereotype/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalTypes" upperBound="-1"
        eType="#//MExternal" containment="true" eOpposite="#//MExternal/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmiGuid" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" upperBound="-1"
        eType="#//MComment" containment="true" eOpposite="#//MComment/owningElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValue" upperBound="-1"
        eType="#//MTaggedValue" containment="true" eOpposite="#//MTaggedValue/owningElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" upperBound="-1"
        eType="#//MStereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspect" upperBound="-1"
        eType="#//MAspect" containment="true" eOpposite="#//MAspect/element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MProperty" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
        eType="#//MClassifier" changeable="false" eOpposite="#//MClassifier/property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericRealization" upperBound="-1"
        eType="#//MGeneric" containment="true" eOpposite="#//MGeneric/owningProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MInterface" eSuperTypes="#//MClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="MClassifier" abstract="true" eSuperTypes="#//MElement #//MType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningPackage" lowerBound="1"
        eType="#//MPackage" changeable="false" eOpposite="#//MPackage/classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
        eType="#//MOperation" containment="true" eOpposite="#//MOperation/classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="#//MProperty" containment="true" eOpposite="#//MProperty/classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericParameter" upperBound="-1"
        eType="#//MGeneric" containment="true" eOpposite="#//MGeneric/owningClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" upperBound="-1"
        eType="#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realization" upperBound="-1"
        eType="#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" upperBound="-1"
        eType="#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" upperBound="-1"
        eType="#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOperation" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//MParameter" containment="true" eOpposite="#//MParameter/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
        eType="#//MClassifier" changeable="false" eOpposite="#//MClassifier/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericParameter" upperBound="-1"
        eType="#//MGeneric" containment="true" eOpposite="#//MGeneric/owningOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raisedException" upperBound="-1"
        eType="#//MType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
        eType="#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MParameter" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultvalue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//MOperation" changeable="false" eOpposite="#//MOperation/parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericRealization" upperBound="-1"
        eType="#//MGeneric" containment="true" eOpposite="#//MGeneric/owningParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//MType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDataType" eSuperTypes="#//MClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="MPrimitiveType" eSuperTypes="#//MType #//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//MModel"
        changeable="false" eOpposite="#//MModel/primitiveTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEnumeration" eSuperTypes="#//MDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" upperBound="-1"
        eType="#//MLiteral" containment="true" eOpposite="#//MLiteral/owningEnumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MStereotype" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="#//MTag" containment="true" eOpposite="#//MTag/stereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//MModel"
        changeable="false" eOpposite="#//MModel/anyStereotype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" lowerBound="1"
        eType="#//MStereotype" changeable="false" eOpposite="#//MStereotype/property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MComment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmiGuid" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annotation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningElement" lowerBound="1"
        eType="#//MElement" changeable="false" eOpposite="#//MElement/ownedComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedComment" upperBound="-1"
        eType="#//MComment" containment="true" eOpposite="#//MComment/nestingComment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestingComment" eType="#//MComment"
        changeable="false" eOpposite="#//MComment/nestedComment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTaggedValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningElement" lowerBound="1"
        eType="#//MElement" changeable="false" eOpposite="#//MElement/taggedValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tag" lowerBound="1" eType="#//MTag"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAspect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//MElement" changeable="false" eOpposite="#//MElement/aspect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="introduction" upperBound="-1"
        eType="#//MIntroduction" containment="true" eOpposite="#//MIntroduction/origin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pointcut" upperBound="-1"
        eType="#//MPointcut" containment="true" eOpposite="#//MPointcut/origin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MIntroduction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="#//MAspect" changeable="false" eOpposite="#//MAspect/introduction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MPointcut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" lowerBound="1"
        eType="#//MDestinationKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="#//MAspect" changeable="false" eOpposite="#//MAspect/pointcut"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MLiteral" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningEnumeration" lowerBound="1"
        eType="#//MEnumeration" changeable="false" eOpposite="#//MEnumeration/literal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MGeneric" eSuperTypes="#//MType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningClassifier" lowerBound="1"
        eType="#//MClassifier" changeable="false" eOpposite="#//MClassifier/genericParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningOperation" lowerBound="1"
        eType="#//MOperation" changeable="false" eOpposite="#//MOperation/genericParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningProperty" lowerBound="1"
        eType="#//MProperty" changeable="false" eOpposite="#//MProperty/genericRealization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningParameter" lowerBound="1"
        eType="#//MParameter" changeable="false" eOpposite="#//MParameter/genericRealization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningExternal" lowerBound="1"
        eType="#//MExternal" changeable="false" eOpposite="#//MExternal/genericParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MExternal" eSuperTypes="#//MType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//MModel"
        changeable="false" eOpposite="#//MModel/externalTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericParameter" upperBound="-1"
        eType="#//MGeneric" containment="true" eOpposite="#//MGeneric/owningExternal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MDestinationKind">
    <eLiterals name="onEntry" value="1"/>
    <eLiterals name="onExit" value="2"/>
    <eLiterals name="onException" value="3"/>
    <eLiterals name="around" value="4"/>
    <eLiterals name="external" value="5"/>
  </eClassifiers>
</ecore:EPackage>
